export const initialStudents = [

    {
        id: 123,
        name: "Lennart",
        secondName: "Grönemeyer",
        birthday: "28.01.2000",
        group: "Javascript",
        sex: "boy",
        email: "lennart.groememeyer@email.de",
        phone: "0175 45 67 8",
    },
    {
        name: "Felix",
        secondName: "Sturm",
        id: 456,
        birthday: "28.01.2000",
        group: "Javascript",
        sex: "boy",
        email: "felix.kamrani@sturm.de",
        phone: "0175 45 67 8",
    },
    {
        id: 789,
        name: "Julia",
        secondName: "Roberts",
        birthday: "28.01.2000",
        group: "Javascript",
        sex: "girl",
        email: "julia.roberts@email.de",

        phone: "0175 45 67 8",
    },
    {
        id: 987,
        name: "Birk",
        secondName: "Schneider",
        birthday: "28.01.2000",
        group: "Javascript",
        sex: "boy",
        email: "birk.schneider@email.de",
        phone: "0175 45 67 8",
    },
    {
        id: 987,
        name: "Yana",
        secondName: "Klitschko",
        birthday: "28.01.2000",
        group: "Javascript",
        sex: "girl",
        email: "yana.klitschko@email.de",
        phone: "0175 45 67 8",
    },
]
